# nixpacks.toml

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "npm install",
    "npm run build",
    "php artisan config:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
# Alterado de "command" para "cmd" para alinhar com a documentação.
cmd = "ln -sfn $PERSISTENT_STORAGE_PATH public/storage && heroku-php-apache2 public/"