databases:
  - name: jobsprout-db
    plan: free
    region: frankfurt
    ipAllowList: []

services:
  - type: web
    name: jobsprout
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /up
    
    envVars:
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: jobsprout-db
          property: connectionString 
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
