# render.yaml - Versão Final

databases:
  - name: jobsprout-db
    plan: free
    region: frankfurt
    ipAllowList: []

services:
  - type: web
    name: jobsprout
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /
    buildCommand: "php artisan config:clear && php artisan route:cache && php artisan view:cache"
    startCommand: "nginx -t && /usr/local/bin/entrypoint.sh" # O comando para iniciar seu servidor
    envVars:
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: ASSET_URL
        value: https
      - key: DATABASE_URL
        fromDatabase:
          name: jobsprout-db
          property: internalConnectionString
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false

jobs:
  - type: pre_deploy # Roda antes de um novo deploy ser ativado
    name: migrate
    plan: free
    dockerCommand: "php artisan migrate --force"