# render.yaml - Corrigido e Otimizado

databases:
  - name: jobsprout-db
    plan: free
    region: frankfurt
    ipAllowList: [] # Perfeito para segurança

services:
  - type: web
    name: jobsprout
    runtime: docker # 'runtime' é a chave correta, 'env' está obsoleto
    plan: free
    region: frankfurt
    healthCheckPath: /

    envVars:
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: ASSET_URL
        value: https
      - key: DATABASE_URL
        fromDatabase:
          name: jobsprout-db
          property: connectionString
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false